apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template-2
  title: python-template-2
  description: Dummy template 2
  tags:
    - recommended
    - python
spec:
  owner: v-jwysokinski@expediagroup.com
  type: service
  parameters:
    - title: Provide information about project
      required:
        - project_name
        - owner
      properties:
        project_name:
          title: project name
          type: string
          description: Unique name of the project
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: desc
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: testing dependencies
      required:
        - storageClassName
      properties:
        storageClassName:
          title: Storage Class Name
          type: string
          description: The storage class name
          default: nfs-client
          enum:
            - nfs-client
            - data-nfs-client
            - local-storage
      dependencies:
        storageClassName:
          oneOf:
            - properties:
                storageClassName:
                  enum:
                    - nfs-client
                    - data-nfs-client
                nfsServer:
                  title: NFS Server
                  type: string
                  description: The NFS server
                  default: 10.0.0.12
                nfsPath:
                  title: NFS Path
                  type: string
                  description: The NFS path
                  default: /mnt/user/kube_storage/python-sample-app
            - properties:
                storageClassName:
                  enum:
                    - local-storage
                localPath:
                  title: Local Path
                  type: string
                  description: The local path
                  default: /mnt/local/python-sample-app

  steps:
    - id: fetch-base
      name: Fetch and filling template
      action: fetch:cookiecutter
      input:
        url: templates
        copyWithoutRender:
          - template_1
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        sourcePath: template_2
        allowedHosts:
          - github.com
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - name: Results
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}