ARG PYTHON_VERSION="3.11"
FROM mcr.microsoft.com/vscode/devcontainers/python:${PYTHON_VERSION}

# Install NodeJS
ARG NODE_VERSION="lts/*"
RUN su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1" \
    && npm install --global yarn

RUN apt-get update \
    && apt-get install git \
    && pip install --upgrade pip

COPY requirements_dev.txt .
RUN pip install -r requirements_dev.txt \
    && rm -f requirements_dev.txt
