apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.project_name}}
  description: {{cookiecutter.description}}
  docs:
    file: docs/docs.yaml
  annotations:
    github.com/project-slug: {{cookiecutter.destination.repo}}
    backstage.io/techdocs-ref: dir:.

  tags:
      - python
      - CostCenter-{{cookiecutter.cost_center_tag}}
      - {{cookiecutter.brand_tag}}
      - {{cookiecutter.team_tag}}
      - {{cookiecutter.environment_tag}}
      - {{cookiecutter.application_tag}}
{%- for data_classification_tag in cookiecutter.data_classification_tags %}
      - {{ data_classification_tag }}
{% endfor %}
spec:
  type: service
  lifecycle: experimental  # TODO change to "production" when basic functionality works
  owner: {{cookiecutter.owner}}

# TODO add more parameters, see them at https://backstage.io/docs/features/software-catalog/descriptor-format/
