apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.project_name}}
  description: {{cookiecutter.description}}
  docs:
    file: docs/docs.yaml
  annotations:
    github.com/project-slug: {{cookiecutter.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    {% cookiecutter.jira_project_key != "" %}
    jira/project-key: {{ cookiecutter.jira_project_key }}
    {% endif %}
  tags:
      - python
spec:
  type: website
  lifecycle: experimental  # TODO change to "production" when basic functionality works
  owner: {{cookiecutter.owner}}

# TODO add more parameters, see them at https://backstage.io/docs/features/software-catalog/descriptor-format/
