name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Change String Case
        id: organization
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io  # TODO SS
          username: ${{ github.actor }}  # TODO SS
          password: ${{ secrets.GITHUB_TOKEN }}  # TODO SS

      - name: Build and push base image
        id: build_base
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile.base
          tags: ghcr.io/${{ steps.organization.outputs.lowercase }}/base-image:latest

      - name: Build and push test image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile.test
          tags: ghcr.io/${{ steps.organization.outputs.lowercase }}/test-image:latest
          build-args: |
            BASE_IMAGE=ghcr.io/${{ steps.organization.outputs.lowercase }}/base-image:latest